### ISSUE TITLE
Best way of upgrading node to a newer version?

### ISSUE THREAD

**Issue by biofreeze** [blinklabs-io/docker-cardano-node#105]
Hi, first off thank you for this awesome repo! Been trying to find a way to run a Cardano Node with Docker but also have the ability to restore from a snapshot with ease :) 

I'm wondering what the best approach is to update the Cardano Node in general. Let's say there's a version bump or something. The general command i'm using to start the Cardano Node is:
```
docker run --detach \
  --name cardano-node \
  -v node-data:/opt/cardano/data \
  -v node-ipc:/opt/cardano/ipc \
  -p 3001:3001 \
  ghcr.io/blinklabs-io/cardano-node run
  ```

Let's say there's a new version, what would I need to do to update to it? Appreciate any info you can provide :)

**Comment by wolf31o2** [comment]
Remove the container. Your data is persistent. Containers are ephemeral.

Delete the container and pull the latest version...

```
docker rm -f cardano-node
docker pull ghcr.io/blinklabs-io/docker-cardano-node
```

After that, re-run your start command.

**Comment by biofreeze** [comment]
Awesome! Thanks so much @wolf31o2 :)

**Comment by wolf31o2** [comment]
No problem. The `-v node-data:/opt/cardano/data` created a `node-data` Docker volume, which is persistent. 🫡
