### ISSUE TITLE
Error: Can not verify the certificate chain from certificate_hash in mainnet

### ISSUE THREAD

**Issue by Fr3chdax** [blinklabs-io/docker-cardano-node#143]
I'm getting the following error when I try to run the container in mainnet.

`snapshot command is deprecated, use cardano-db instead
Starting: /usr/local/bin/mithril-client snapshot download 79d4ad40116ecb2afd9025d7799f264d38a4624055e4de3d1b358d30769a626c
snapshot command is deprecated, use cardano-db instead
Error: Can not verify the certificate chain from certificate_hash: 'ef8318584d1a389f8efacaec273bab7bfd5cb98e76682fa6bd05334d73210066'

Caused by:
    0: Certicate chain of certificate 'ef8318584d1a389f8efacaec273bab7bfd5cb98e76682fa6bd05334d73210066' is invalid
    1: certificate hash unmatch error`
    
Is this a known error or am I doing something wrong?

When I run the container in preprod it is working just fine. The container is also running correctly when RESTORE_SNAPSHOT=false but then Mithril is not used.

**Comment by wolf31o2** [comment]
It's a known error. Mithril just released a breaking change.

I'm working on the upgrade here: blinklabs-io/docker-mithril-client#29

**Comment by Fr3chdax** [comment]
Thanks for the fast response. Shall I close the issue?

**Comment by wolf31o2** [comment]
Nah, I'll close it today when I fix the issue.

**Comment by wolf31o2** [comment]
This is fixed in v8.9.2-4
